version: '2'

services:
  mongo:  
    image: mvertes/alpine-mongo:3.2.3
    volumes:
      - /home/pwiklowski/iot/database:/data/db
    ports:
      - "27017:27017"
    command: mongod --smallfiles

  dbbackend:
    ports:
      - "7001:7001"
    build:
      context: .
      dockerfile: Dockerfile-gobackend

  iotserver:
    network_mode: "host"
    build:
      context: .
      dockerfile: Dockerfile-iot-server

  webui:
    network_mode: "host"
    build:
      context: .
      dockerfile: Dockerfile-webui
