version: '2'

services:
  mongo:  
    image: mvertes/alpine-mongo:latest
    volumes:
      - /home/pawwik/dev/iot-webui-2/mydatabase:/data/db
    ports:
      - "27017:27017"
    command: mongod --smallfiles

  dbbackend:
    ports:
      - "7001:7001"
    build:
      context: .
      dockerfile: Dockerfile-gobackend

  iotserver:
    build:
      context: .
      dockerfile: Dockerfile-iot-server

  webui:
    ports:
      - "7000:7000"
    build:
      context: .
      dockerfile: Dockerfile-webui
